package com.astropinterest.apod.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@NoArgsConstructor
@ToString
@JsonIgnoreProperties(ignoreUnknown = true)
public class Apod implements Serializable {

    private String concept_tag;   // "concept_tags functionality turned off in current service"
    private String copyright;     // "Jarmo RuuthTelescope LiveHeaven's Mirror Observatory"
    private String date;          // "2022-01-17"
    private String explanation;   // "Sometimes the dark dust of interstellar space has an angular elegance. Such is the case toward the far-south constellation of Chamaeleon. Normally too faint to see, dark dust is best known for blocking visible light from stars and galaxies behind it. In this four-hour exposure, however, the dust is seen mostly in light of its own, with its strong red and near-infrared colors giving creating a brown hue. Contrastingly blue, the bright star Beta Chamaeleontis is visible just to the right of center, with the dust that surrounds it preferentially reflecting blue light from its primarily blue-white color. All of the pictured stars and dust occur in our own Milky Way Galaxy with -- but one notable exception: the white spot just below Beta Chamaeleontis is the galaxy IC 3104 which lies far in the distance. Interstellar dust is mostly created in the cool atmospheres of giant stars and dispersed into space by stellar light, stellar winds, and stellar explosions such as supernovas."
    private String hdurl;         // "https://apod.nasa.gov/apod/image/2201/DarkNebulaVd_HmoRuuth_4096.jpg"
    private String media_type;    // "image"
    private String service_version; // "v1"
    private String title;         // "Chamaeleon Dark Nebulas"
    private String url;           // "https://apod.nasa.gov/apod/image/2201/DarkNebulaVd_HmoRuuth_960.jpg"
    private String errorMessage;  // Passback the error message is generated by the local backend if there are something wrongs.
}